---
driver:
  name: vagrant
  config:
    require_chef_omnibus: true

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/integration/default/tk_encrypted_data_bag_secret
  data_bags_path: test/integration/default/data_bags
  environment: _default

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[s3cmdng::default]
    attributes:
      s3cmdng:
        users:
          - root
          - vagrant
