name             's3cmdng'
maintainer       'E Camden Fisher'
maintainer_email 'camden@northpage.com'
license          'Apache 2.0'
description      'Installs/Configures s3cmd'
long_description 'Installs/Configures s3cmd'
version          '0.1.3'
depends 'yum'
depends 'yum-epel'
