name             's3cmdng'
maintainer       'E Camden Fisher'
maintainer_email 'camden@northpage.com'
license          'Apache 2.0'
description      'Installs/Configures s3cmd'
long_description 'Installs/Configures s3cmd'
version          '0.1.1'
depends 'yum', '~> 3.4.1'
depends 'yum-epel', '~> 0.5.2'
